CREATE TABLE Usuario (
Id AUTO_INCREMENT INTEGER PRIMARY KEY,
Email VARCHAR(255) UNIQUE NOT NULL,
Nome VARCHAR(255) NOT NULL,
Senha VARCHAR(255) NOT NULL,
image_path VARCHAR(255),
horas TIME NOT NULL,
Cargo VARCHAR(255) NOT NULL,
Departamento VARCHAR(255) NOT NULL,
estalecadas INTEGER NOT NULL,
isAdmin INTEGER NOT NULL,
esta_na_sede INTEGER NOT NULL,
leu_mensagem INTEGER
);

CREATE TABLE Horarios (
Id INTEGER PRIMARY KEY,
Entrada DATETIME NOT NULL,
Saida DATETIME NOT NULL,
IdUsuario INTEGER,
Atividade VARCHAR(255),
Departamento VARCHAR(100),
FOREIGN KEY(IdUsuario) REFERENCES Usuario (Id)
);

